version: 0.2

env:
  variables:
    AWS_ACCESS_KEY_ID: "AKIAZ4FC45AGP77UPF3T"
    AWS_SECRET_ACCESS_KEY: "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"
    AWS_DEFAULT_REGION: "us-west-2"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      #- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 678946465804.dkr.ecr.us-west-2.amazonaws.com
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=678946465804.dkr.ecr.us-west-2.amazonaws.com/node-ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      #- docker build -t node-ecr .
      #- docker tag node-ecr:latest 678946465804.dkr.ecr.us-west-2.amazonaws.com/node-ecr:latest
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #- docker push 678946465804.dkr.ecr.us-west-2.amazonaws.com/node-ecr:latest
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"node-app","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      #- printf '[{"name":"node-app","imageUri":"%s"}]' 678946465804.dkr.ecr.us-west-2.amazonaws.com/node-ecr:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
